service: test-api
frameworkVersion: '3'

plugins:
  - serverless-prune-plugin
  - serverless-plugin-monorepo
  - serverless-dotenv-plugin

custom:
  envConfig: ${file(./config/${opt:stage}.config.json)}
  prune:
    automatic: true
    number: 2
  cors:
    origin: '*'
    headers:
      - authorization
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
    allowCredentials: false

provider:
  name: aws
  stage: dev
  runtime: nodejs16.x
  region: 'eu-west-3'
  environment:
    LOG_LEVEL: ${self:custom.envConfig.logLevel}
  deploymentBucket:
    blockPublicAccess: true
  logs:
    restApi: true
  vpc: ${self:custom.envConfig.vpc}

package:
  excludeDevDependencies: true

functions:
  exercises_getExercise:
    handler: dist/exercises/controller/getExercise/handler.default
    events:
      - http:
          path: exercises/{id}
          method: get
  exercises_getExercises:
    handler: dist/exercises/controller/getExercises/handler.default
    events:
      - http:
          path: exercises/{id}
          method: get